package com.p2p.gui;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import java.awt.*;
import java.awt.event.*;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.DefaultTableCellRenderer;

import java.io.*;

import javax.imageio.*;
import java.net.*;

import com.p2p.client.ClientReceiveBean;
import com.p2p.client.ClientSendBean;
import com.p2p.client.ClientSendFile;
import com.p2p.util.*;

public class MainJFrame extends javax.swing.JFrame {

	/** Creates new form MainJFrame */
	public MainJFrame(String username, String ip, int port) {

		initComponents();
		
		currentUser.setText(username);
		currentIP.setText(ip);
		currentPort.setText(port + "");

		deleteButton.setEnabled(false);

		//填充表格的数据
		FileInfoModel start = new FileInfoModel(null);
		jTableFileInfo.setModel(start);
		DefaultTableCellRenderer render = new DefaultTableCellRenderer();
		render.setHorizontalAlignment(JLabel.CENTER);
		jTableFileInfo.setDefaultRenderer(Object.class, render);
		//更新数据完毕

		this.username = username;
		this.clientIP = ip;
		this.clientPort = port;

		this.enableEvents(AWTEvent.WINDOW_EVENT_MASK);
		int width = Toolkit.getDefaultToolkit().getScreenSize().width;
		int height = Toolkit.getDefaultToolkit().getScreenSize().height;
		this.setLocation(width / 2 - 400, height / 2 - 250);
		this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		this.setVisible(true);
		this.setResizable(false);


		//开启客户端点对点传输文件进程ClientSendFile
		new ClientSendFile(this.clientPort);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		checkButton = new javax.swing.JButton();
		deleteButton = new javax.swing.JButton();
		uploadButton = new javax.swing.JButton();
		downloadButton = new javax.swing.JButton();
		jTextFieldKeyWord = new javax.swing.JTextField();
		jLabelKeyWord = new javax.swing.JLabel();
		searchButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableFileInfo = new javax.swing.JTable();
		jLabelCurrentIP = new javax.swing.JLabel();
		jLabelCurrentUser = new javax.swing.JLabel();
		jLabelCurrentPort = new javax.swing.JLabel();
		jLabelDownLoadOver = new javax.swing.JLabel();
		showAllButton = new javax.swing.JButton();
		currentUser = new javax.swing.JLabel();
		currentIP = new javax.swing.JLabel();
		currentPort = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("P2P\u6587\u4ef6\u5171\u4eab\u7cfb\u7edf");
		setResizable(false);

		checkButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		checkButton.setText("\u67e5\u770b");
		checkButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkButtonActionPerformed(evt);
			}
		});

		deleteButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		deleteButton.setText("\u5220\u9664");
		deleteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteButtonActionPerformed(evt);
			}
		});

		uploadButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		uploadButton.setText("\u4e0a\u4f20");
		uploadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				uploadButtonActionPerformed(evt);
			}
		});

		downloadButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		downloadButton.setText("\u4e0b\u8f7d");
		downloadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				downloadButtonActionPerformed(evt);
			}
		});

		jLabelKeyWord.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabelKeyWord.setText("\u5173\u952e\u5b57:");

		searchButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		searchButton.setText("\u641c\u7d22");
		searchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchButtonActionPerformed(evt);
			}
		});

		jTableFileInfo.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTableFileInfo.setCellSelectionEnabled(true);
		jScrollPane1.setViewportView(jTableFileInfo);

		jLabelCurrentIP.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabelCurrentIP.setText("IP\u5730\u5740:");

		jLabelCurrentUser.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabelCurrentUser.setText("\u5f53\u524d\u7528\u6237:");

		jLabelCurrentPort.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabelCurrentPort.setText("\u7aef\u53e3\u53f7:");

		jLabelDownLoadOver.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabelDownLoadOver.setForeground(new java.awt.Color(0, 0, 255));
		jLabelDownLoadOver
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		showAllButton.setFont(new java.awt.Font("微软雅黑", 1, 12));
		showAllButton.setText("\u670d\u52a1\u5668\u6587\u4ef6\u5217\u8868");
		showAllButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showAllButtonActionPerformed(evt);
			}
		});

		currentUser.setForeground(java.awt.Color.red);

		currentIP.setForeground(java.awt.Color.red);

		currentPort.setForeground(java.awt.Color.red);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 3, 24));
		jLabel1.setText("P2P\u6587\u4ef6\u5171\u4eab\u7cfb\u7edf");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				26,
																				26,
																				26)
																		.addComponent(
																				jLabelCurrentUser,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				82,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				currentUser,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				78,
																				Short.MAX_VALUE)
																		.addGap(
																				124,
																				124,
																				124)
																		.addComponent(
																				jLabelCurrentIP,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				77,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				currentIP,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				78,
																				Short.MAX_VALUE)
																		.addGap(
																				81,
																				81,
																				81)
																		.addComponent(
																				jLabelCurrentPort,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				79,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				currentPort,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				80,
																				Short.MAX_VALUE)
																		.addGap(
																				40,
																				40,
																				40))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				22,
																				22,
																				22)
																		.addComponent(
																				jLabelKeyWord,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				47,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextFieldKeyWord,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				200,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				28,
																				28,
																				28)
																		.addComponent(
																				searchButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				40,
																				40,
																				40)
																		.addComponent(
																				showAllButton))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				647,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								downloadButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								100,
																								Short.MAX_VALUE)
																						.addComponent(
																								checkButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								100,
																								Short.MAX_VALUE)
																						.addComponent(
																								deleteButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								100,
																								Short.MAX_VALUE)
																						.addComponent(
																								uploadButton,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								100,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabelDownLoadOver,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								100,
																								Short.MAX_VALUE))))
										.addContainerGap()).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(281, 281,
										281).addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										298, Short.MAX_VALUE).addGap(199, 199,
										199)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelKeyWord)
														.addComponent(
																searchButton)
														.addComponent(
																jTextFieldKeyWord,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																showAllButton))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				34,
																				34,
																				34)
																		.addComponent(
																				checkButton)
																		.addGap(
																				37,
																				37,
																				37)
																		.addComponent(
																				deleteButton)
																		.addGap(
																				39,
																				39,
																				39)
																		.addComponent(
																				uploadButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				25,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				43,
																				43,
																				43)
																		.addComponent(
																				downloadButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				25,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				26,
																				26,
																				26)
																		.addComponent(
																				jLabelDownLoadOver,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				31,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				296,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(24, 24, 24)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.CENTER)
														.addComponent(
																jLabelCurrentUser)
														.addComponent(
																currentUser)
														.addComponent(
																jLabelCurrentIP)
														.addComponent(currentIP)
														.addComponent(
																jLabelCurrentPort)
														.addComponent(
																currentPort))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	
	
	protected void processWindowEvent(WindowEvent e) 
	{  
        super.processWindowEvent(e);  
        if (e.getID() == WindowEvent.WINDOW_CLOSING) 
        {  
        	this.updateUserInfo("0");
        }
        else if (e.getID() == WindowEvent.WINDOW_OPENED) 
        {
        	this.updateUserInfo("1");
        }
    }  
	
	//窗口关闭前更新用户在线状态为"否"以及更新实时IP地址
	public void updateUserInfo(String online)
	{
		//获取本机实时IP地址
    	InetAddress addr = null;
		try {
			addr = InetAddress.getLocalHost();
		} catch (UnknownHostException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		String ip=addr.getHostAddress().toString();//获得本机IP
    	ClientSendBean csbUpdate=new ClientSendBean(null,0,"updateUserInfo",username,ip,online);
    	
    	//接收验证结果
		ClientReceiveBean crb = new ClientReceiveBean("updateUserInfo", null,
				null, this, csbUpdate);
	}
	
	private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int rowIndex = jTableFileInfo.getSelectedRow();

		if (rowIndex == -1) {
			JOptionPane.showMessageDialog(null, "请选择下载文件!", "消息",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		//若用户不在线，则提示无法下载信息
		if (((String) fim.getValueAt(rowIndex, 6)).equals("否")) {
			JOptionPane.showMessageDialog(null, "文件拥有者不在线,无法下载!", "消息",
					JOptionPane.ERROR_MESSAGE);
			return;
		}

		//获取文件名,路径，大小等信息
		String fname = (String) fim.getValueAt(rowIndex, 0);
		String fpath = (String) fim.getValueAt(rowIndex, 1);
		String fsize = (String) fim.getValueAt(rowIndex, 2);
		String newFsize = fsize.substring(0, fsize.indexOf("K"));

		String ip = (String) fim.getValueAt(rowIndex, 4);
		String port = (String) fim.getValueAt(rowIndex, 5);

		//test
		FileDialog fd = new FileDialog(this, "另存为", FileDialog.SAVE);
		fd.setFile(fname);
		fd.setDirectory("C:\\");
		fd.show();
		//

		String savePath = fd.getDirectory();
		String saveFname = fd.getFile();

		if (saveFname == null) {
			System.out.println("download command cancelled by user");
			return;
		}

		// 将文件信息传递给ClientBean
		ClientSendBean csb = new ClientSendBean(ip, Integer.parseInt(port), "downloadFile",
				fname, fpath, newFsize);

		//接收验证结果
		ClientReceiveBean crb = new ClientReceiveBean("downloadFile", null,
				null, this, csb);
		crb.setSavePath(savePath);
		crb.setFilename(saveFname);

	}

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int rowIndex = jTableFileInfo.getSelectedRow();

		if (rowIndex == -1) {
			JOptionPane.showMessageDialog(null, "请选择一行!", "消息",
					JOptionPane.ERROR_MESSAGE);
			return;
		}
		String fname = (String) fim.getValueAt(rowIndex, 0);

		// 将数据传递给ClientBean
		ClientSendBean csb = null;

		//用户名和密码传给服务器,进行登录验证

		csb = new ClientSendBean(null, 0, "deleteFile", fname);
		//cb.DeleteFileInfo(fname);

		//接收验证结果
		ClientReceiveBean crb = new ClientReceiveBean("deleteFile", null, null,
				this, csb);
		
	}

	public void ProcessQuery(int type) {
		// 将数据传递给ClientBean
		ClientSendBean csb = new ClientSendBean(null, 0, "queryFile", 
				jTextFieldKeyWord.getText(), username, type + "");

		//接收验证结果
		ClientReceiveBean crb = new ClientReceiveBean("queryFile", null, null,
				this, csb);
	}

	private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextFieldKeyWord.setText("");
		this.ProcessQuery(3);
		deleteButton.setEnabled(true);
	}

	private void showAllButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextFieldKeyWord.setText("");
		this.ProcessQuery(2);
		deleteButton.setEnabled(false);
	}

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jTextFieldKeyWord.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "查询条件为空,请重新输入!", "消息",
					JOptionPane.ERROR_MESSAGE);
		} else {
			this.ProcessQuery(1);
		}
		deleteButton.setEnabled(false);
	}

	private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		JFileChooser filechooser = new JFileChooser();
		filechooser.setDialogTitle("请选择上传文件");
		filechooser.setFileSelectionMode(0);
		filechooser.setCurrentDirectory(new File("C:\\"));
		int returnVal = filechooser.showOpenDialog(this);

		File file;
		long fileLength;

		if (returnVal == JFileChooser.CANCEL_OPTION) {
			System.out.println("upload command cancelled by user");
			return;
		}

		// selected the current file or directroy
		file = filechooser.getSelectedFile();

		// Find the length of the file
		if (file != null) {
			fileLength = file.length();
			String filePath = file.getPath();

			String newFile = filePath.substring(0, filePath.lastIndexOf('\\'));

			StringBuffer sb = new StringBuffer(newFile);
			for (int i = 0; i < sb.length(); i++) {
				if (sb.charAt(i) == '\\') {
					sb.insert(i, '\\');
					i++;
				}
			}

			String fileName = file.getName();

			// 将数据传递给ClientBean
			ClientSendBean csb = null;
			//用户名和密码传给服务器,进行登录验证
			csb = new ClientSendBean(null, 0, "uploadFile", fileName, sb
					.toString(), fileLength + "K", username);
			//csb.SubmitFileInfo(fileName, sb.toString(), fileLength + "K",username);

			//接收验证结果
			ClientReceiveBean crb = new ClientReceiveBean("uploadFile", null,
					null, this, csb);
			
		}
	}

	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton checkButton;
	public javax.swing.JLabel currentIP;
	public javax.swing.JLabel currentPort;
	public javax.swing.JLabel currentUser;
	public javax.swing.JButton deleteButton;
	private javax.swing.JButton downloadButton;
	private javax.swing.JLabel jLabel1;
	public javax.swing.JLabel jLabelCurrentIP;
	public javax.swing.JLabel jLabelCurrentPort;
	public javax.swing.JLabel jLabelCurrentUser;
	public javax.swing.JLabel jLabelDownLoadOver;
	public javax.swing.JLabel jLabelKeyWord;
	private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTable jTableFileInfo;
	public javax.swing.JTextField jTextFieldKeyWord;
	private javax.swing.JButton searchButton;
	private javax.swing.JButton showAllButton;
	private javax.swing.JButton uploadButton;
	// End of variables declaration//GEN-END:variables

	private String username;
	private String clientIP;
	private int clientPort;

	private String savePath;
	private String filename;
	//表模式
	public FileInfoModel fim;

}